import test, { beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import request from 'supertest';
import { createApp } from '../src/app.js';
import { importData, signed } from '../src/import-data.js';
import { Store, makeSessionStore } from '../src/store.js';

let temp; let dataFile; let app;
beforeEach(() => { temp = fs.mkdtempSync(path.join(os.tmpdir(), 'carddemo-')); dataFile = path.join(temp, 'carddemo.json'); importData(dataFile); app = createApp({ dataFile, sessionSecret: 'test-session-secret-that-is-long-enough-for-tests' }); });
async function login(agent, userId = 'USER0001', password = 'User123!') { return agent.post('/api/auth/sign-in').send({ userId, password }).expect(200); }

test('COBOL overpunch parser handles positive and negative implied decimals', () => { assert.equal(signed('0000005047G'), 504.77); assert.equal(signed('0000009190}'), -919); assert.equal(signed('0000000678H'), 67.88); assert.equal(signed('0000000010J'), -1.01); assert.equal(signed('0000000010R'), -1.09); });
test('auth isolation, role split, menu and malformed body responses work', async () => {
  const first = request.agent(app); const second = request.agent(app); await login(first); await second.get('/api/auth/me').expect(401); await first.get('/api/admin/users').expect(403); await first.get('/api/menu').expect(200).expect(r => assert.equal(r.body.data.length, 5));
  const admin = request.agent(app); const response = await login(admin, 'ADMIN001', 'Admin123!'); assert.equal(response.body.data.menu.length, 4); assert.ok(!JSON.stringify(response.body).includes('passwordHash')); await request(app).post('/api/auth/sign-in').set('Content-Type', 'application/json').send('{bad').expect(400).expect(r => assert.equal(r.body.error.code, 'INVALID_JSON'));
});
test('account/customer data masks secrets and supports customer ETags', async () => {
  const agent = request.agent(app); await login(agent); const account = await agent.get('/api/accounts/00000000001').expect(200); assert.equal(account.body.data.version, undefined); assert.match(account.body.data.customers[0].ssn, /^\*+/);
  const customer = await agent.get(`/api/accounts/00000000001/customers/${account.body.data.customers[0].id}`).expect(200); const url = `/api/accounts/00000000001/customers/${customer.body.data.id}`; await agent.patch(url).set('If-Match', customer.headers.etag).send({ dob:'2024-02-30' }).expect(422); await agent.patch(url).set('If-Match', customer.headers.etag).send({ governmentId:customer.body.data.governmentId }).expect(422); await agent.patch(url).set('If-Match', customer.headers.etag).send({ phone1:'555-555-5555' }).expect(200); await agent.patch(url).set('If-Match', customer.headers.etag).send({ phone2:'this-is-more-than-fifteen' }).expect(422);
});
test('pagination, card pair validation, lookup and not-found routes validate inputs', async () => {
  const agent = request.agent(app); await login(agent); await agent.get('/api/cards').expect(200).expect(r => assert.equal(r.body.data.page.limit, 7)); await agent.get('/api/cards?limit=x').expect(400); await agent.get('/api/cards?cursor=nope').expect(400); await agent.get('/api/cards?accountId=00000000001&cardNumber=0683586198171516').expect(404); await agent.get('/api/lookup/transaction-types').expect(200).expect(r => assert.ok(r.body.data.length)); await agent.get('/api/lookup/transaction-categories?typeCode=01').expect(200).expect(r => assert.ok(r.body.data.length)); await agent.get('/not-a-route').expect(404);
});
test('transaction preserves COTRN02 source parity and rejects idempotency reuse', async () => {
  const agent = request.agent(app); await login(agent); const card = (await agent.get('/api/cards?accountId=00000000001&limit=1')).body.data.items[0]; const balance = (await agent.get('/api/accounts/00000000001')).body.data.currentBalance;
  const payload = { cardNumber:card.number, typeCode:'01', categoryCode:'0001', source:'API', description:'test purchase', amount:12.34 }; const first = await agent.post('/api/transactions').set('Idempotency-Key','transaction-key-unique').send(payload).expect(201); const replay = await agent.post('/api/transactions').set('Idempotency-Key','transaction-key-unique').send(payload).expect(200); assert.equal(first.body.data.id, replay.body.data.id); assert.equal((await agent.get('/api/accounts/00000000001')).body.data.currentBalance, balance); await agent.post('/api/transactions').set('Idempotency-Key','transaction-key-unique').send({ ...payload, amount:13 }).expect(409); await agent.post('/api/transactions').send(payload).expect(400); await agent.patch(`/api/cards/${card.number}`).set('If-Match', (await agent.get(`/api/cards/${card.number}`)).headers.etag).send({ active:'N' }).expect(200); await agent.post('/api/transactions').set('Idempotency-Key','inactive-card-key').send(payload).expect(422);
});
test('billing uses xref, returns updated account, and idempotency detects different targets', async () => {
  const agent = request.agent(app); await login(agent); const account = await agent.get('/api/accounts/00000000002'); const first = await agent.post('/api/billing/00000000002/pay-full-balance').set('If-Match',account.headers.etag).set('Idempotency-Key','payment-key-unique').send({}).expect(201); assert.equal(first.body.data.account.currentBalance, 0); assert.ok(first.headers.etag); await agent.post('/api/billing/00000000002/pay-full-balance').set('Idempotency-Key','payment-key-unique').send({}).expect(200); await agent.post('/api/billing/00000000001/pay-full-balance').set('Idempotency-Key','payment-key-unique').send({}).expect(409); await agent.post('/api/billing/00000000002/pay-full-balance').set('If-Match',first.headers.etag).set('Idempotency-Key','second-payment-key').send({}).expect(409).expect(r => assert.equal(r.body.error.code,'NOTHING_TO_PAY'));
});
test('reports use imported originatedAt fallback, are owner restricted and include totals', async () => {
  const admin = request.agent(app); await login(admin, 'ADMIN001', 'Admin123!'); await admin.post('/api/admin/users').send({ id:'USER0002', firstName:'Second', lastName:'User', role:'U', password:'UserTwo1!' }).expect(201);
  const one = request.agent(app); const two = request.agent(app); await login(one); await login(two, 'USER0002', 'UserTwo1!'); const created = await one.post('/api/reports').send({ period:'custom', startDate:'2022-06-01', endDate:'2022-06-30' }).expect(201); const content = await one.get(`/api/reports/${created.body.data.id}/content`).expect(200); assert.match(content.text, /0000000000683580/); assert.match(content.text, /Account Total/); assert.match(content.text, /Grand Total/); await two.get(`/api/reports/${created.body.data.id}`).expect(403); await one.post('/api/reports').send({ period:'custom',startDate:'2023-02-29',endDate:'2023-03-01' }).expect(422); await one.post('/api/reports').send({ period:'monthly' }).expect(201); await one.post('/api/reports').send({ period:'yearly' }).expect(201);
});
test('user safeguards prevent self-delete and last-admin deletion, and deleted users lose access', async () => { const admin = request.agent(app); await login(admin,'ADMIN001','Admin123!'); const own = await admin.get('/api/admin/users/ADMIN001'); await admin.delete('/api/admin/users/ADMIN001').set('If-Match',own.headers.etag).expect(409).expect(r => assert.equal(r.body.error.code, 'LAST_ADMIN_FORBIDDEN')); const second = await admin.post('/api/admin/users').send({ id:'ADMIN002',firstName:'Second',lastName:'Admin',role:'A',password:'LongPass1' }).expect(201); const user = await admin.post('/api/admin/users').send({ id:'TESTUSER',firstName:'Test',lastName:'User',role:'U',password:'LongPass1' }).expect(201); await admin.get('/api/admin/users?limit=1').expect(200).expect(r => assert.equal(r.body.data.page.limit,1)); const userSession = request.agent(app); await login(userSession,'TESTUSER','LongPass1'); await admin.delete('/api/admin/users/TESTUSER').set('If-Match',user.headers.etag).expect(204); await userSession.get('/api/menu').expect(401).expect(r => assert.equal(r.body.error.code, 'SESSION_REVOKED')); const secondUser = await admin.get('/api/admin/users/ADMIN002'); await admin.delete('/api/admin/users/ADMIN002').set('If-Match',secondUser.headers.etag).expect(204); const stale = await admin.get('/api/admin/users/ADMIN001'); await admin.patch('/api/admin/users/ADMIN001').set('If-Match','\"0\"').send({ firstName:'New' }).expect(412); await admin.patch('/api/admin/users/ADMIN001').set('If-Match',stale.headers.etag).send({ firstName:'Admin' }).expect(200); });
test('store snapshot rolls back callback errors and session store directly prunes expired sessions', async () => { const store = new Store(dataFile); const before = structuredClone(store.load().accounts[0]); assert.throws(() => store.transaction(data => { data.accounts[0].zip = 'bad'; throw new Error('rollback'); })); assert.deepEqual(store.load().accounts[0], before); store.transaction(data => { data.sessions.expired = { expiresAt:Date.now()-1,session:{user:{id:'USER0001',role:'U'},cookie:{}} }; }); const sessions = makeSessionStore(store); const found = await new Promise((resolve, reject) => sessions.get('expired', (error, value) => error ? reject(error) : resolve(value))); assert.equal(found, null); assert.equal(store.load().sessions.expired, undefined); });
