import express from 'express';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import { PgSessionStore } from './session-store.js';
import { createPool, formatTimestamp } from './db.js';
import { createRepository, account as mapAccount } from './repositories/carddemo.js';

const id = value => String(value ?? '').trim();
const money = value => Math.round(Number(value) * 100) / 100;
const appError = (status, code, message, details) => Object.assign(new Error(message), { status, code, details });
const etag = value => `"${value.version}"`;
const digits = (value, width, name) => { const result=id(value); if(!new RegExp(`^\\d{${width}}$`).test(result)) throw appError(422,'VALIDATION_ERROR',`${name} must be exactly ${width} characters.`); return result; };
const dateOnly = value => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`)) && new Date(`${value}T00:00:00Z`).toISOString().slice(0,10) === value;
const mask = value => value ? `${'*'.repeat(Math.max(0,String(value).length-4))}${String(value).slice(-4)}` : '';
const publicAccount=({version,...v})=>v; const publicCard=({cvv,version,...v})=>v; const publicTransaction=({version,...v})=>v; const publicUser=({passwordHash,version,...v})=>v;
const publicCustomer=({ssn,governmentId,eftAccountId,version,...v})=>({...v,ssn:mask(ssn),governmentId:mask(governmentId),eftAccountId:mask(eftAccountId)});
const required=(body, fields)=>{const missing=fields.filter(k=>body[k]===undefined||body[k]===null||body[k]==='');if(missing.length)throw appError(422,'VALIDATION_ERROR','Required fields are missing.',{missing});};
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`:JSON.stringify(value);
const normalizeTimestamp = value => { const parsed = new Date(value); return `${parsed.getUTCFullYear()}-${String(parsed.getUTCMonth()+1).padStart(2,'0')}-${String(parsed.getUTCDate()).padStart(2,'0')} ${String(parsed.getUTCHours()).padStart(2,'0')}:${String(parsed.getUTCMinutes()).padStart(2,'0')}:${String(parsed.getUTCSeconds()).padStart(2,'0')}.${String(parsed.getUTCMilliseconds()*1000).padStart(6,'0')}`; };
const asyncRoute = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);
function pagination(values, limit, defaultLimit) { if(limit!==undefined&&(!/^\d+$/.test(String(limit))||Number(limit)<1||Number(limit)>100))throw appError(400,'INVALID_LIMIT','limit must be an integer from 1 through 100.'); const size=limit===undefined?defaultLimit:Number(limit); const page=values.slice(0,size); return {items:page,page:{limit:size,nextCursor:values.length>size?(page.at(-1).id??page.at(-1).number):null}}; }
function menu(role) { return role==='A'?[{key:'users-list',label:'List users',href:'/api/admin/users'},{key:'users-create',label:'Create user',href:'/api/admin/users'},{key:'users-update',label:'Update user',href:'/api/admin/users/{userId}'},{key:'users-delete',label:'Delete user',href:'/api/admin/users/{userId}'}]:[{key:'accounts',label:'Account view/update',href:'/api/accounts/{accountId}'},{key:'cards',label:'Cards',href:'/api/cards'},{key:'transactions',label:'Transactions',href:'/api/transactions'},{key:'billing',label:'Bill payment',href:'/api/billing/{accountId}/preview'},{key:'reports',label:'Transaction reports',href:'/api/reports'}]; }
function assertMatch(req, value) { if(!req.get('If-Match'))throw appError(428,'PRECONDITION_REQUIRED','If-Match is required for this mutation.'); if(req.get('If-Match')!==etag(value))throw appError(412,'VERSION_CONFLICT','Resource has changed; fetch it and retry.'); }
function assertPatch(body, allowed, message='At least one mutable field is required.') { for(const key of Object.keys(body))if(!allowed.includes(key))throw appError(422,'VALIDATION_ERROR',`Unsupported ${allowed===cardFields?'card':allowed===userFields?'user':allowed===customerFields?'customer':'account'} field: ${key}`); if(!Object.keys(body).length)throw appError(422,'VALIDATION_ERROR',message); }
const accountFields=['active','creditLimit','cashCreditLimit','zip','groupId','expirationDate','reissueDate']; const customerFields=['firstName','middleName','lastName','address1','address2','address3','state','country','zip','phone1','phone2','dob','primaryCardHolder','fico']; const cardFields=['active','embossedName','expirationDate']; const userFields=['firstName','lastName','role','password'];
function validateAccount(body){assertPatch(body,accountFields);if('active'in body&&!['Y','N'].includes(body.active))throw appError(422,'VALIDATION_ERROR','active must be Y or N.');for(const k of ['creditLimit','cashCreditLimit'])if(k in body&&(!Number.isFinite(Number(body[k]))||Number(body[k])<0||Number(body[k])>9999999999.99))throw appError(422,'VALIDATION_ERROR',`${k} must be a non-negative amount within PIC S9(10)V99.`);if('zip'in body&&(id(body.zip).length<1||id(body.zip).length>10))throw appError(422,'VALIDATION_ERROR','zip must be 1-10 characters.');if('groupId'in body&&id(body.groupId).length>10)throw appError(422,'VALIDATION_ERROR','groupId must be at most 10 characters.');for(const k of ['expirationDate','reissueDate'])if(k in body&&!dateOnly(body[k]))throw appError(422,'VALIDATION_ERROR',`${k} must be a real YYYY-MM-DD date.`);}
function validateCustomer(body){assertPatch(body,customerFields);for(const k of ['firstName','middleName','lastName'])if(k in body&&(id(body[k]).length<1||id(body[k]).length>25))throw appError(422,'VALIDATION_ERROR',`${k} must be 1-25 characters.`);for(const k of ['address1','address2','address3'])if(k in body&&id(body[k]).length>50)throw appError(422,'VALIDATION_ERROR',`${k} must be at most 50 characters.`);if('state'in body&&id(body.state).length!==2)throw appError(422,'VALIDATION_ERROR','state must be exactly 2 characters.');if('country'in body&&id(body.country).length!==3)throw appError(422,'VALIDATION_ERROR','country must be exactly 3 characters.');if('zip'in body&&(id(body.zip).length<1||id(body.zip).length>10))throw appError(422,'VALIDATION_ERROR','zip must be 1-10 characters.');for(const k of ['phone1','phone2'])if(k in body&&!/^[0-9+(). -]{1,15}$/.test(id(body[k])))throw appError(422,'VALIDATION_ERROR',`${k} must be a legacy-compatible phone value of at most 15 digits/punctuation characters.`);if('dob'in body&&!dateOnly(body.dob))throw appError(422,'VALIDATION_ERROR','dob must be a real YYYY-MM-DD date.');if('primaryCardHolder'in body&&!['Y','N'].includes(body.primaryCardHolder))throw appError(422,'VALIDATION_ERROR','primaryCardHolder must be Y or N.');if('fico'in body&&(!Number.isInteger(Number(body.fico))||Number(body.fico)<300||Number(body.fico)>850))throw appError(422,'VALIDATION_ERROR','fico must be an integer from 300 through 850.');}
function transactionBody(body){required(body,['cardNumber','typeCode','categoryCode','source','description','amount']);const cardNumber=digits(body.cardNumber,16,'cardNumber'),typeCode=digits(body.typeCode,2,'typeCode'),categoryCode=digits(String(body.categoryCode).padStart(4,'0'),4,'categoryCode');if(id(body.source).length<1||id(body.source).length>10||id(body.description).length<1||id(body.description).length>100)throw appError(422,'VALIDATION_ERROR','source must be 1-10 and description 1-100 characters.');if(!Number.isFinite(Number(body.amount))||Number(body.amount)===0||Math.abs(Number(body.amount))>999999999.99)throw appError(422,'VALIDATION_ERROR','amount must be non-zero and fit PIC S9(9)V99.');for(const k of ['merchantName','merchantCity'])if(k in body&&id(body[k]).length>50)throw appError(422,'VALIDATION_ERROR',`${k} must be at most 50 characters.`);if('merchantId'in body)digits(body.merchantId,9,'merchantId');if('merchantZip'in body&&id(body.merchantZip).length>10)throw appError(422,'VALIDATION_ERROR','merchantZip must be at most 10 characters.');for(const k of ['originatedAt','processedAt'])if(k in body&&(typeof body[k]!=='string'||Number.isNaN(Date.parse(body[k]))))throw appError(422,'VALIDATION_ERROR',`${k} must be an ISO-parseable timestamp.`);return {cardNumber,typeCode,categoryCode,source:id(body.source),description:id(body.description),amount:money(body.amount),merchantId:body.merchantId?digits(body.merchantId,9,'merchantId'):'000000000',merchantName:id(body.merchantName).slice(0,50),merchantCity:id(body.merchantCity).slice(0,50),merchantZip:id(body.merchantZip).slice(0,10),originatedAt:body.originatedAt ? normalizeTimestamp(body.originatedAt) : formatTimestamp(),processedAt:body.processedAt ? normalizeTimestamp(body.processedAt) : formatTimestamp()};}

export function createApp({ pool = createPool(), repository = createRepository(pool), sessionSecret=process.env.SESSION_SECRET, trustProxy=process.env.TRUST_PROXY }={}) {
  if(process.env.NODE_ENV==='production'&&!sessionSecret)throw new Error('SESSION_SECRET must be configured in production.'); const app=express(); app.disable('x-powered-by'); if(trustProxy!==undefined&&trustProxy!=='')app.set('trust proxy',trustProxy==='true'?true:/^\d+$/.test(String(trustProxy))?Number(trustProxy):trustProxy);
  app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Cache-Control':'no-store'});next();}); app.use(express.json({limit:'100kb',strict:true})); app.use(session({store:new PgSessionStore(pool),name:'carddemo.sid',secret:sessionSecret||'development-only-secret-change-before-production',resave:false,saveUninitialized:false,rolling:false,cookie:{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}}));
  const requireAuth=asyncRoute(async(req,_res,next)=>{const identity=req.session.user;if(!identity)throw appError(401,'UNAUTHENTICATED','Sign in is required.');const current=await repository.getUser(identity.id);if(!current||current.role!==identity.role)return req.session.destroy(()=>next(appError(401,'SESSION_REVOKED','This session is no longer authorized.')));next();}); const business=[requireAuth,(req,_res,next)=>req.session.user.role==='U'?next():next(appError(403,'FORBIDDEN','Business endpoints require a U role.'))];const admin=[requireAuth,(req,_res,next)=>req.session.user.role==='A'?next():next(appError(403,'FORBIDDEN','Administrative endpoints require an A role.'))];
  const accountId=req=>digits(req.params.accountId,11,'accountId'),customerId=req=>digits(req.params.customerId,9,'customerId'),cardNumber=req=>digits(req.params.cardNumber,16,'cardNumber'); const userId=req=>{const value=id(req.params.userId).toUpperCase();if(!/^[A-Z0-9]{3,8}$/.test(value))throw appError(422,'VALIDATION_ERROR','userId must be 3-8 uppercase alphanumeric characters.');return value;}; const idem=(req,target)=>{const key=req.get('Idempotency-Key');if(!key||!/^[\x21-\x7e]{8,128}$/.test(key))throw appError(400,'IDEMPOTENCY_KEY_REQUIRED','An Idempotency-Key of 8-128 visible ASCII characters is required.');return {key,target,fingerprint:stable(req.body??{})};};
  app.get('/health',(_q,res)=>res.json({data:{status:'ok'}}));
  app.post('/api/auth/sign-in',asyncRoute(async(req,res,next)=>{required(req.body,['userId','password']);const value=await repository.getUser(id(req.body.userId).toUpperCase());if(!value||!(await bcrypt.compare(String(req.body.password),value.passwordHash)))throw appError(401,'INVALID_CREDENTIALS','Invalid user ID or password.');req.session.regenerate(error=>{if(error)return next(error);req.session.user={id:value.id,role:value.role};req.session.save(error=>{if(error)return next(error);return res.json({data:{user:publicUser(value),menu:menu(value.role)}});});});})); app.post('/api/auth/sign-out',requireAuth,(req,res,next)=>req.session.destroy(error=>error?next(error):(res.clearCookie('carddemo.sid'),res.status(204).end())));app.get('/api/auth/me',requireAuth,(req,res)=>res.json({data:{user:req.session.user}}));app.get('/api/menu',requireAuth,(req,res)=>res.json({data:menu(req.session.user.role)}));
  app.get('/api/accounts/:accountId',business,asyncRoute(async(req,res)=>{const value=await repository.accountView(accountId(req));if(!value)throw appError(404,'NOT_FOUND','Account not found.');res.set('ETag',etag(value)).json({data:{...publicAccount(value),customers:value.customers.map(publicCustomer),cards:value.cards.map(publicCard)}});}));
  app.patch('/api/accounts/:accountId',business,asyncRoute(async(req,res)=>{validateAccount(req.body);const before=await repository.getAccount(accountId(req));if(!before)throw appError(404,'NOT_FOUND','Account not found.');assertMatch(req,before);const patch={...req.body};for(const k of ['creditLimit','cashCreditLimit'])if(k in patch)patch[k]=money(patch[k]);const value=await repository.update('accounts','id',before.id,before.version,patch);if(!value)throw appError(412,'VERSION_CONFLICT','Resource has changed; fetch it and retry.');res.set('ETag',etag(value)).json({data:publicAccount(value)});}));
  app.get('/api/accounts/:accountId/customers/:customerId',business,asyncRoute(async(req,res)=>{const a=accountId(req),c=customerId(req);if(!(await repository.isAssociated(a,c)))throw appError(404,'NOT_FOUND','Customer is not associated with this account.');const value=await repository.getCustomer(c);res.set('ETag',etag(value)).json({data:publicCustomer(value)});}));
  app.patch('/api/accounts/:accountId/customers/:customerId',business,asyncRoute(async(req,res)=>{validateCustomer(req.body);const a=accountId(req),c=customerId(req);if(!(await repository.isAssociated(a,c)))throw appError(404,'NOT_FOUND','Customer is not associated with this account.');const before=await repository.getCustomer(c);assertMatch(req,before);const patch={...req.body};if('fico'in patch)patch.fico=Number(patch.fico);const value=await repository.update('customers','id',c,before.version,patch);if(!value)throw appError(412,'VERSION_CONFLICT','Resource has changed; fetch it and retry.');res.set('ETag',etag(value)).json({data:publicCustomer(value)});}));
  app.get('/api/cards', business, asyncRoute(async (req, res) => {
    const accountIdQ = req.query.accountId && digits(req.query.accountId, 11, 'accountId');
    const cardNumberQ = req.query.cardNumber && digits(req.query.cardNumber, 16, 'cardNumber');
    if (req.query.cursor && !/^\d{16}$/.test(id(req.query.cursor))) throw appError(400, 'INVALID_CURSOR', 'Cursor does not identify a resource in this result set.');
    const size = req.query.limit === undefined ? 7 : Number(req.query.limit);
    if (!Number.isInteger(size) || size < 1 || size > 100) throw appError(400, 'INVALID_LIMIT', 'limit must be an integer from 1 through 100.');
    const values = await repository.listCards({ accountId: accountIdQ, cardNumber: cardNumberQ, cursor: req.query.cursor, limit: size });
    if (values === null) throw appError(400, 'INVALID_CURSOR', 'Cursor does not identify a resource in this result set.');
    if (accountIdQ && cardNumberQ && !req.query.cursor && !values.length) throw appError(404, 'NOT_FOUND', 'Card is not associated with this account.');
    res.json({ data: pagination(values.map(publicCard), req.query.limit, 7) });
  }));
  app.get('/api/cards/:cardNumber',business,asyncRoute(async(req,res)=>{const value=await repository.getCard(cardNumber(req));if(!value)throw appError(404,'NOT_FOUND','Card not found.');res.set('ETag',etag(value)).json({data:publicCard(value)});})); app.patch('/api/cards/:cardNumber',business,asyncRoute(async(req,res)=>{assertPatch(req.body,cardFields,'Card fields are invalid.');if(('active'in req.body&&!['Y','N'].includes(req.body.active))||('embossedName'in req.body&&(id(req.body.embossedName).length<1||id(req.body.embossedName).length>50))||('expirationDate'in req.body&&!dateOnly(req.body.expirationDate)))throw appError(422,'VALIDATION_ERROR','Card fields are invalid.');const before=await repository.getCard(cardNumber(req));if(!before)throw appError(404,'NOT_FOUND','Card not found.');assertMatch(req,before);const value=await repository.update('cards','number',before.number,before.version,req.body);if(!value)throw appError(412,'VERSION_CONFLICT','Resource has changed; fetch it and retry.');res.set('ETag',etag(value)).json({data:publicCard(value)});}));
  app.get('/api/lookup/transaction-types',business,asyncRoute(async(_q,res)=>res.json({data:await repository.types()}))); app.get('/api/lookup/transaction-categories',business,asyncRoute(async(req,res)=>{const type=req.query.typeCode&&digits(req.query.typeCode,2,'typeCode');res.json({data:await repository.categories(type)});}));
  app.get('/api/transactions', business, asyncRoute(async (req, res) => {
    const cardQ = req.query.cardNumber && digits(req.query.cardNumber, 16, 'cardNumber');
    const accountQ = req.query.accountId && digits(req.query.accountId, 11, 'accountId');
    if (req.query.cursor && !/^\d{16}$/.test(id(req.query.cursor))) throw appError(400, 'INVALID_CURSOR', 'Cursor does not identify a resource in this result set.');
    const size = req.query.limit === undefined ? 10 : Number(req.query.limit);
    if (!Number.isInteger(size) || size < 1 || size > 100) throw appError(400, 'INVALID_LIMIT', 'limit must be an integer from 1 through 100.');
    const values = await repository.listTransactions({ accountId: accountQ, cardNumber: cardQ, cursor: req.query.cursor, limit: size });
    if (values === null) throw appError(400, 'INVALID_CURSOR', 'Cursor does not identify a resource in this result set.');
    res.json({ data: pagination(values.map(publicTransaction), req.query.limit, 10) });
  })); app.get('/api/transactions/:transactionId',business,asyncRoute(async(req,res)=>{const value=await repository.getTransaction(digits(req.params.transactionId,16,'transactionId'));if(!value)throw appError(404,'NOT_FOUND','Transaction not found.');res.set('ETag',etag(value)).json({data:publicTransaction(value)});}));
  app.post('/api/transactions',business,asyncRoute(async(req,res)=>{const info=idem(req,'POST:/api/transactions');const result=await repository.withTransaction(async db=>repository.idempotency(db,req.session.user.id,info.key,info.target,info.fingerprint,async()=>{const value=transactionBody(req.body);if(!(await repository.definedType(value.typeCode,value.categoryCode,db)))throw appError(422,'VALIDATION_ERROR','typeCode/categoryCode is not defined.');const card=await repository.getCard(value.cardNumber,db);if(!card||card.active!=='Y')throw appError(422,'VALIDATION_ERROR','cardNumber must identify an active card.');return {transaction:publicTransaction(await repository.insertTransaction(db,value))};}));res.status(result.replay?200:201).set('ETag','"1"').json({data:result.transaction,meta:{idempotentReplay:result.replay}});}));
  app.get('/api/billing/:accountId/preview',business,asyncRoute(async(req,res)=>{const value=await repository.getAccount(accountId(req));if(!value)throw appError(404,'NOT_FOUND','Account not found.');res.set('ETag',etag(value)).json({data:{accountId:value.id,currentBalance:value.currentBalance,amountDue:Math.max(value.currentBalance,0),payable:value.currentBalance>0}});}));
  app.post('/api/billing/:accountId/pay-full-balance',business,asyncRoute(async(req,res)=>{const a=accountId(req),info=idem(req,`POST:/api/billing/${a}/pay-full-balance`);const result=await repository.withTransaction(async db=>repository.idempotency(db,req.session.user.id,info.key,info.target,info.fingerprint,async()=>{const before=await repository.getAccount(a,db,true);if(!before)throw appError(404,'NOT_FOUND','Account not found.');assertMatch(req,before);if(before.currentBalance<=0)throw appError(409,'NOTHING_TO_PAY','Account has no outstanding balance.');const x=await db.query('SELECT c.* FROM cards c JOIN card_xrefs x ON x.card_number=c.number AND x.account_id=c.account_id WHERE x.account_id=$1 ORDER BY c.number LIMIT 1',[a]);if(!x.rowCount)throw appError(422,'VALIDATION_ERROR','Account has no card cross-reference for payment.');const now=formatTimestamp(),tx=await repository.insertTransaction(db,{typeCode:'02',categoryCode:'0002',source:'POS TERM',description:'BILL PAYMENT - ONLINE',amount:before.currentBalance,merchantId:'999999999',merchantName:'BILL PAYMENT',merchantCity:'N/A',merchantZip:'N/A',cardNumber:x.rows[0].number,originatedAt:now,processedAt:now});const updated=await db.query('UPDATE accounts SET current_balance=0,current_cycle_credit=current_cycle_credit+$1,version=version+1 WHERE id=$2 RETURNING *',[before.currentBalance,a]);const after=mapAccount(updated.rows[0]);return {transaction:publicTransaction(tx),account:publicAccount(after),accountEtag:etag(after)};}));res.status(result.replay?200:201).set('ETag',result.accountEtag).json({data:{transaction:result.transaction,account:result.account},meta:{idempotentReplay:result.replay}});}));
  app.post('/api/reports',business,asyncRoute(async(req,res)=>{let {startDate,endDate}=req.body; const period=req.body.period || 'custom';const now=new Date();if(period==='monthly'){startDate=`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,'0')}-01`;endDate=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0)).toISOString().slice(0,10);}else if(period==='yearly'){startDate=`${now.getUTCFullYear()}-01-01`;endDate=`${now.getUTCFullYear()}-12-31`;}else if(period!=='custom')throw appError(422,'VALIDATION_ERROR','period must be monthly, yearly, or custom.');if(!dateOnly(startDate)||!dateOnly(endDate)||startDate>endDate)throw appError(422,'VALIDATION_ERROR','Use an ordered range of real YYYY-MM-DD dates.');const rs=await repository.reportRows(startDate,endDate),totals=new Map();for(const r of rs)totals.set(r.accountId,money((totals.get(r.accountId)||0)+r.amount));const content=['Daily Transaction Report',`Date Range: ${startDate} to ${endDate}`,'Transaction ID     Account ID   Type Category Source       Amount',...rs.map(r=>`${r.id} ${r.accountId.padEnd(11)} ${r.typeCode}   ${r.categoryCode}     ${r.source.padEnd(10)} ${r.amount.toFixed(2)}`),'',...[...totals.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([a,total])=>`Account Total ${a}: ${total.toFixed(2)}`),`Grand Total: ${money(rs.reduce((sum,r)=>sum+r.amount,0)).toFixed(2)}`].join('\n');const value=await repository.withTransaction(db=>repository.createReport(db,{ownerId:req.session.user.id,period,startDate,endDate,content}));res.status(201).json({data:{id:value.id,status:value.status,period:value.period,startDate:value.startDate,endDate:value.endDate}});}));
  const own=async req=>{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id(req.params.reportId)))throw appError(404,'NOT_FOUND','Report not found.');const value=await repository.getReport(id(req.params.reportId));if(!value)throw appError(404,'NOT_FOUND','Report not found.');if(value.ownerId!==req.session.user.id)throw appError(403,'FORBIDDEN','Report belongs to another user.');return value;}; app.get('/api/reports/:reportId',business,asyncRoute(async(req,res)=>{const value=await own(req);res.json({data:{id:value.id,status:value.status,period:value.period,startDate:value.startDate,endDate:value.endDate,createdAt:value.createdAt}});}));app.get('/api/reports/:reportId/content',business,asyncRoute(async(req,res)=>{const value=await own(req);if(value.status!=='completed')throw appError(409,'REPORT_NOT_READY','Report has not completed.');res.type('text/plain').send(value.content);}));
  app.get('/api/admin/users',admin,asyncRoute(async(req,res)=>{if(req.query.cursor){const value=id(req.query.cursor).toUpperCase();if(!/^[A-Z0-9]{3,8}$/.test(value))throw appError(400,'INVALID_CURSOR','Cursor does not identify a resource in this result set.');}const size=req.query.limit===undefined?10:Number(req.query.limit);if(!Number.isInteger(size)||size<1||size>100)throw appError(400,'INVALID_LIMIT','limit must be an integer from 1 through 100.');const values=await repository.listUsers({cursor:req.query.cursor,limit:size});if(values===null)throw appError(400,'INVALID_CURSOR','Cursor does not identify a resource in this result set.');res.json({data:pagination(values.map(publicUser),req.query.limit,10)});}));
  app.post('/api/admin/users',admin,asyncRoute(async(req,res)=>{required(req.body,['id','firstName','lastName','password','role']);const value={id:id(req.body.id).toUpperCase(),firstName:id(req.body.firstName),lastName:id(req.body.lastName),role:req.body.role};if(!/^[A-Z0-9]{3,8}$/.test(value.id)||!['A','U'].includes(value.role)||!value.firstName||value.firstName.length>25||!value.lastName||value.lastName.length>25||String(req.body.password).length<8)throw appError(422,'VALIDATION_ERROR','id, firstName, lastName, role A/U, and password of at least 8 characters are required.');value.passwordHash=await bcrypt.hash(String(req.body.password),12);try{const created=await repository.withTransaction(async db=>value.role==='A'?repository.withAdminLock(db,()=>repository.createUser(db,value)):repository.createUser(db,value));res.status(201).set('ETag',etag(created)).json({data:publicUser(created)});}catch(error){if(error.code==='23505')throw appError(409,'ALREADY_EXISTS','User already exists.');throw error;}}));
  app.get('/api/admin/users/:userId',admin,asyncRoute(async(req,res)=>{const value=await repository.getUser(userId(req));if(!value)throw appError(404,'NOT_FOUND','User not found.');res.set('ETag',etag(value)).json({data:publicUser(value)});}));
  app.patch('/api/admin/users/:userId',admin,asyncRoute(async(req,res)=>{assertPatch(req.body,userFields,'User fields are invalid.');if(('role'in req.body&&!['A','U'].includes(req.body.role))||('firstName'in req.body&&(!id(req.body.firstName)||id(req.body.firstName).length>25))||('lastName'in req.body&&(!id(req.body.lastName)||id(req.body.lastName).length>25))||('password'in req.body&&String(req.body.password).length<8))throw appError(422,'VALIDATION_ERROR','User fields are invalid.');const target=userId(req);const before=await repository.getUser(target);if(!before)throw appError(404,'NOT_FOUND','User not found.');assertMatch(req,before);const patch={};for(const key of ['firstName','lastName','role'])if(key in req.body)patch[key]=id(req.body[key]);if(req.body.password)patch.passwordHash=await bcrypt.hash(String(req.body.password),12);const roleChanges=patch.role&&patch.role!==before.role;const value=await repository.withTransaction(async db=>{const mutate=async()=>{const current=await repository.getUser(target,db);if(!current)throw appError(404,'NOT_FOUND','User not found.');if(current.version!==before.version)throw appError(412,'VERSION_CONFLICT','Resource has changed; fetch it and retry.');if(current.role==='A'&&patch.role==='U'&&await repository.adminCount(db)===1)throw appError(409,'LAST_ADMIN_FORBIDDEN','The last administrator cannot be removed.');return repository.update('users','id',target,current.version,patch,db);};return roleChanges?repository.withAdminLock(db,mutate):mutate();});res.set('ETag',etag(value)).json({data:publicUser(value)});}));
  app.delete('/api/admin/users/:userId',admin,asyncRoute(async(req,res)=>{
    const target=userId(req); const before=await repository.getUser(target);
    if(!before)throw appError(404,'NOT_FOUND','User not found.');
    const count=await repository.withTransaction(async db=>{
      const mutate=async()=>{
        const current=await repository.getUser(target,db);
        if(!current)throw appError(404,'NOT_FOUND','User not found.');
        assertMatch(req,current);
        if(current.role==='A'&&await repository.adminCount(db)===1)throw appError(409,'LAST_ADMIN_FORBIDDEN','The last administrator cannot be deleted.');
        if(current.id===req.session.user.id)throw appError(409,'SELF_DELETE_FORBIDDEN','An administrator cannot delete their own active user.');
        return repository.deleteUser(db,target,current.version);
      };
      return before.role==='A'?repository.withAdminLock(db,mutate):mutate();
    });
    if(!count)throw appError(412,'VERSION_CONFLICT','Resource has changed; fetch it and retry.');
    res.status(204).end();
  }));
  app.use((_q,_r,next)=>next(appError(404,'NOT_FOUND','Route not found.')));app.use((error,_req,res,_next)=>{const malformed=error instanceof SyntaxError&&'body'in error,invalidPath=error instanceof URIError;res.status(malformed||invalidPath?400:error.status||500).json({error:{code:malformed?'INVALID_JSON':invalidPath?'INVALID_PATH':error.code||'INTERNAL_ERROR',message:malformed?'Request body must be valid JSON.':invalidPath?'Path contains invalid URL encoding.':error.status?error.message:'An unexpected server error occurred.',...(error.details?{details:error.details}:{})}});}); return app;
}
