import express from 'express';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { Store, makeSessionStore } from './store.js';

const money = value => Math.round(Number(value) * 100) / 100;
const id = value => String(value ?? '').trim();
const appError = (status, code, message, details) => Object.assign(new Error(message), { status, code, details });
const etag = entity => `"${entity.version}"`;
const requireFields = (body, fields) => { const missing = fields.filter(key => body[key] === undefined || body[key] === null || body[key] === ''); if (missing.length) throw appError(422, 'VALIDATION_ERROR', 'Required fields are missing.', { missing }); };
const fixed = (value, width, name, pattern = /[\s\S]/) => { const result = id(value); if (!new RegExp(`^${pattern.source}{${width}}$`).test(result)) throw appError(422, 'VALIDATION_ERROR', `${name} must be exactly ${width} characters.`); return result; };
const digits = (value, width, name) => fixed(value, width, name, /\d/);
const dateOnly = value => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`)) && new Date(`${value}T00:00:00Z`).toISOString().slice(0, 10) === value;
const timestamp = value => typeof value === 'string' && !Number.isNaN(Date.parse(value));
const mask = value => value ? `${'*'.repeat(Math.max(0, String(value).length - 4))}${String(value).slice(-4)}` : '';
const publicCard = ({ cvv, version, ...card }) => card;
const publicCustomer = ({ ssn, governmentId, eftAccountId, version, ...customer }) => ({ ...customer, ssn: mask(ssn), governmentId: mask(governmentId), eftAccountId: mask(eftAccountId) });
const publicAccount = ({ version, ...account }) => account;
const publicTransaction = ({ version, ...transaction }) => transaction;
const publicUser = ({ passwordHash, version, ...user }) => user;
function requireMatch(req, entity) { if (!req.get('If-Match')) throw appError(428, 'PRECONDITION_REQUIRED', 'If-Match is required for this mutation.'); if (req.get('If-Match') !== etag(entity)) throw appError(412, 'VERSION_CONFLICT', 'Resource has changed; fetch it and retry.'); }
function pagination(items, cursor, limit, defaultLimit) {
  if (limit !== undefined && (!/^\d+$/.test(String(limit)) || Number(limit) < 1 || Number(limit) > 100)) throw appError(400, 'INVALID_LIMIT', 'limit must be an integer from 1 through 100.');
  const size = limit === undefined ? defaultLimit : Number(limit);
  const start = cursor ? items.findIndex(item => (item.id ?? item.number) === id(cursor)) + 1 : 0;
  if (cursor && start === 0) throw appError(400, 'INVALID_CURSOR', 'Cursor does not identify a resource in this result set.');
  const slice = items.slice(start, start + size);
  return { items: slice, page: { limit: size, nextCursor: start + slice.length < items.length && slice.length ? (slice.at(-1).id ?? slice.at(-1).number) : null } };
}
function stable(value) { if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`; return JSON.stringify(value); }
function effectiveDate(transaction) { return (transaction.processedAt || transaction.originatedAt || '').slice(0, 10); }
function accountView(data, account) {
  const xrefs = data.xrefs.filter(x => x.accountId === account.id);
  return { ...publicAccount(account), customers: xrefs.map(x => data.customers.find(c => c.id === x.customerId)).filter(Boolean).map(publicCustomer), cards: xrefs.map(x => data.cards.find(c => c.number === x.cardNumber)).filter(Boolean).map(publicCard) };
}
function menu(role) {
  if (role === 'A') return [
    { key: 'users-list', label: 'List users', href: '/api/admin/users' }, { key: 'users-create', label: 'Create user', href: '/api/admin/users' }, { key: 'users-update', label: 'Update user', href: '/api/admin/users/{userId}' }, { key: 'users-delete', label: 'Delete user', href: '/api/admin/users/{userId}' }
  ];
  return [{ key: 'accounts', label: 'Account view/update', href: '/api/accounts/{accountId}' }, { key: 'cards', label: 'Cards', href: '/api/cards' }, { key: 'transactions', label: 'Transactions', href: '/api/transactions' }, { key: 'billing', label: 'Bill payment', href: '/api/billing/{accountId}/preview' }, { key: 'reports', label: 'Transaction reports', href: '/api/reports' }];
}
function validateAccountPatch(body) {
  const allowed = ['active', 'creditLimit', 'cashCreditLimit', 'zip', 'groupId', 'expirationDate', 'reissueDate'];
  for (const key of Object.keys(body)) if (!allowed.includes(key)) throw appError(422, 'VALIDATION_ERROR', `Unsupported account field: ${key}`);
  if (!Object.keys(body).length) throw appError(422, 'VALIDATION_ERROR', 'At least one mutable field is required.');
  if ('active' in body && !['Y', 'N'].includes(body.active)) throw appError(422, 'VALIDATION_ERROR', 'active must be Y or N.');
  for (const key of ['creditLimit', 'cashCreditLimit']) if (key in body && (!Number.isFinite(Number(body[key])) || Number(body[key]) < 0 || Number(body[key]) > 9999999999.99)) throw appError(422, 'VALIDATION_ERROR', `${key} must be a non-negative amount within PIC S9(10)V99.`);
  if ('zip' in body && (id(body.zip).length < 1 || id(body.zip).length > 10)) throw appError(422, 'VALIDATION_ERROR', 'zip must be 1-10 characters.');
  if ('groupId' in body && id(body.groupId).length > 10) throw appError(422, 'VALIDATION_ERROR', 'groupId must be at most 10 characters.');
  for (const key of ['expirationDate', 'reissueDate']) if (key in body && !dateOnly(body[key])) throw appError(422, 'VALIDATION_ERROR', `${key} must be a real YYYY-MM-DD date.`);
}
function validateCustomerPatch(body) {
  // Sensitive identifiers are deliberately read-only: responses are masked, so accepting them would corrupt values on read-modify-write clients.
  const allowed = ['firstName', 'middleName', 'lastName', 'address1', 'address2', 'address3', 'state', 'country', 'zip', 'phone1', 'phone2', 'dob', 'primaryCardHolder', 'fico'];
  for (const key of Object.keys(body)) if (!allowed.includes(key)) throw appError(422, 'VALIDATION_ERROR', `Unsupported customer field: ${key}`);
  if (!Object.keys(body).length) throw appError(422, 'VALIDATION_ERROR', 'At least one mutable field is required.');
  for (const key of ['firstName', 'middleName', 'lastName']) if (key in body && (id(body[key]).length < 1 || id(body[key]).length > 25)) throw appError(422, 'VALIDATION_ERROR', `${key} must be 1-25 characters.`);
  for (const key of ['address1', 'address2', 'address3']) if (key in body && id(body[key]).length > 50) throw appError(422, 'VALIDATION_ERROR', `${key} must be at most 50 characters.`);
  if ('state' in body && id(body.state).length !== 2) throw appError(422, 'VALIDATION_ERROR', 'state must be exactly 2 characters.');
  if ('country' in body && id(body.country).length !== 3) throw appError(422, 'VALIDATION_ERROR', 'country must be exactly 3 characters.');
  if ('zip' in body && (id(body.zip).length < 1 || id(body.zip).length > 10)) throw appError(422, 'VALIDATION_ERROR', 'zip must be 1-10 characters.');
  for (const key of ['phone1', 'phone2']) if (key in body && !/^[0-9+(). -]{1,15}$/.test(id(body[key]))) throw appError(422, 'VALIDATION_ERROR', `${key} must be a legacy-compatible phone value of at most 15 digits/punctuation characters.`);
  if ('dob' in body && !dateOnly(body.dob)) throw appError(422, 'VALIDATION_ERROR', 'dob must be a real YYYY-MM-DD date.');
  if ('primaryCardHolder' in body && !['Y', 'N'].includes(body.primaryCardHolder)) throw appError(422, 'VALIDATION_ERROR', 'primaryCardHolder must be Y or N.');
  if ('fico' in body && (!Number.isInteger(Number(body.fico)) || Number(body.fico) < 300 || Number(body.fico) > 850)) throw appError(422, 'VALIDATION_ERROR', 'fico must be an integer from 300 through 850.');
}
function validateTransaction(body, data) {
  requireFields(body, ['cardNumber', 'typeCode', 'categoryCode', 'source', 'description', 'amount']);
  digits(body.cardNumber, 16, 'cardNumber'); digits(body.typeCode, 2, 'typeCode'); digits(String(body.categoryCode).padStart(4, '0'), 4, 'categoryCode');
  if (id(body.source).length < 1 || id(body.source).length > 10 || id(body.description).length < 1 || id(body.description).length > 100) throw appError(422, 'VALIDATION_ERROR', 'source must be 1-10 and description 1-100 characters.');
  if (!Number.isFinite(Number(body.amount)) || Number(body.amount) === 0 || Math.abs(Number(body.amount)) > 999999999.99) throw appError(422, 'VALIDATION_ERROR', 'amount must be non-zero and fit PIC S9(9)V99.');
  for (const key of ['merchantName', 'merchantCity']) if (key in body && id(body[key]).length > 50) throw appError(422, 'VALIDATION_ERROR', `${key} must be at most 50 characters.`);
  if ('merchantId' in body) digits(body.merchantId, 9, 'merchantId'); if ('merchantZip' in body && id(body.merchantZip).length > 10) throw appError(422, 'VALIDATION_ERROR', 'merchantZip must be at most 10 characters.');
  for (const key of ['originatedAt', 'processedAt']) if (key in body && !timestamp(body[key])) throw appError(422, 'VALIDATION_ERROR', `${key} must be an ISO-parseable timestamp.`);
  const typeCode = id(body.typeCode); const categoryCode = String(body.categoryCode).padStart(4, '0');
  if (!data.types.some(type => type.code === typeCode) || !data.categories.some(category => category.typeCode === typeCode && category.code === categoryCode)) throw appError(422, 'VALIDATION_ERROR', 'typeCode/categoryCode is not defined.');
}

export function createApp({ dataFile = process.env.DATA_FILE || fileURLToPath(new URL('../data/carddemo.json', import.meta.url)), sessionSecret = process.env.SESSION_SECRET, trustProxy = process.env.TRUST_PROXY } = {}) {
  if (process.env.NODE_ENV === 'production' && !sessionSecret) throw new Error('SESSION_SECRET must be configured in production.');
  const store = new Store(dataFile);
  const app = express();
  app.disable('x-powered-by');
  if (trustProxy !== undefined && trustProxy !== '') app.set('trust proxy', trustProxy === 'true' ? true : (/^\d+$/.test(String(trustProxy)) ? Number(trustProxy) : trustProxy));
  app.use((req, res, next) => { res.set({ 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', 'Cache-Control': 'no-store' }); next(); });
  app.use(express.json({ limit: '100kb', strict: true }));
  const sessions = makeSessionStore(store); Object.setPrototypeOf(sessions, session.Store.prototype);
  app.use(session({ store: sessions, name: 'carddemo.sid', secret: sessionSecret || 'development-only-secret-change-before-production', resave: false, saveUninitialized: false, rolling: false, cookie: { httpOnly: true, sameSite: 'strict', secure: process.env.NODE_ENV === 'production', maxAge: 8 * 60 * 60 * 1000 } }));
  const requireAuth = (req, _res, next) => {
    const identity = req.session.user;
    if (!identity) return next(appError(401, 'UNAUTHENTICATED', 'Sign in is required.'));
    const user = store.load().users.find(item => item.id === identity.id);
    if (!user || user.role !== identity.role) {
      return req.session.destroy(() => next(appError(401, 'SESSION_REVOKED', 'This session is no longer authorized.')));
    }
    return next();
  };
  const business = [requireAuth, (req, _res, next) => req.session.user.role === 'U' ? next() : next(appError(403, 'FORBIDDEN', 'Business endpoints require a U role.'))];
  const admin = [requireAuth, (req, _res, next) => req.session.user.role === 'A' ? next() : next(appError(403, 'FORBIDDEN', 'Administrative endpoints require an A role.'))];
  const accountId = req => digits(req.params.accountId, 11, 'accountId');
  const customerId = req => digits(req.params.customerId, 9, 'customerId');
  const cardNumber = req => digits(req.params.cardNumber, 16, 'cardNumber');
  const userId = req => { const value = id(req.params.userId).toUpperCase(); if (!/^[A-Z0-9]{3,8}$/.test(value)) throw appError(422, 'VALIDATION_ERROR', 'userId must be 3-8 uppercase alphanumeric characters.'); return value; };
  function idempotency(req, target) {
    const key = req.get('Idempotency-Key'); if (!key || !/^[\x21-\x7e]{8,128}$/.test(key)) throw appError(400, 'IDEMPOTENCY_KEY_REQUIRED', 'An Idempotency-Key of 8-128 visible ASCII characters is required.');
    return { key: `${req.session.user.id}:${key}`, target, fingerprint: stable(req.body ?? {}) };
  }
  function replay(data, idem) { const existing = data.idempotency[idem.key]; if (!existing) return null; if (existing.target !== idem.target || existing.fingerprint !== idem.fingerprint) throw appError(409, 'IDEMPOTENCY_CONFLICT', 'Idempotency-Key was already used for a different target or request body.'); return existing.result; }

  app.get('/health', (_req, res) => res.json({ data: { status: 'ok' } }));
  app.post('/api/auth/sign-in', async (req, res, next) => { try { requireFields(req.body, ['userId', 'password']); const user = store.load().users.find(item => item.id === id(req.body.userId).toUpperCase()); if (!user || !(await bcrypt.compare(String(req.body.password), user.passwordHash))) throw appError(401, 'INVALID_CREDENTIALS', 'Invalid user ID or password.'); req.session.regenerate(error => { if (error) return next(error); req.session.user = { id: user.id, role: user.role }; return req.session.save(saveError => saveError ? next(saveError) : res.json({ data: { user: publicUser(user), menu: menu(user.role) } })); }); } catch (error) { next(error); } });
  app.post('/api/auth/sign-out', requireAuth, (req, res, next) => req.session.destroy(error => { if (error) return next(error); res.clearCookie('carddemo.sid'); return res.status(204).end(); }));
  app.get('/api/auth/me', requireAuth, (req, res) => res.json({ data: { user: req.session.user } }));
  app.get('/api/menu', requireAuth, (req, res) => res.json({ data: menu(req.session.user.role) }));

  app.get('/api/accounts/:accountId', business, (req, res, next) => { try { const account = store.load().accounts.find(item => item.id === accountId(req)); if (!account) throw appError(404, 'NOT_FOUND', 'Account not found.'); res.set('ETag', etag(account)).json({ data: accountView(store.load(), account) }); } catch (error) { next(error); } });
  app.patch('/api/accounts/:accountId', business, (req, res, next) => { try { validateAccountPatch(req.body); const account = store.transaction(data => { const value = data.accounts.find(item => item.id === accountId(req)); if (!value) throw appError(404, 'NOT_FOUND', 'Account not found.'); requireMatch(req, value); Object.assign(value, req.body); for (const key of ['creditLimit', 'cashCreditLimit']) if (key in req.body) value[key] = money(value[key]); value.version++; return value; }); res.set('ETag', etag(account)).json({ data: publicAccount(account) }); } catch (error) { next(error); } });
  app.get('/api/accounts/:accountId/customers/:customerId', business, (req, res, next) => { try { const data = store.load(); if (!data.xrefs.some(x => x.accountId === accountId(req) && x.customerId === customerId(req))) throw appError(404, 'NOT_FOUND', 'Customer is not associated with this account.'); const customer = data.customers.find(item => item.id === customerId(req)); res.set('ETag', etag(customer)).json({ data: publicCustomer(customer) }); } catch (error) { next(error); } });
  app.patch('/api/accounts/:accountId/customers/:customerId', business, (req, res, next) => { try { validateCustomerPatch(req.body); const customer = store.transaction(data => { if (!data.xrefs.some(x => x.accountId === accountId(req) && x.customerId === customerId(req))) throw appError(404, 'NOT_FOUND', 'Customer is not associated with this account.'); const value = data.customers.find(item => item.id === customerId(req)); requireMatch(req, value); Object.assign(value, req.body); if ('fico' in req.body) value.fico = Number(value.fico); value.version++; return value; }); res.set('ETag', etag(customer)).json({ data: publicCustomer(customer) }); } catch (error) { next(error); } });

  app.get('/api/cards', business, (req, res, next) => { try { const data = store.load(); if (req.query.accountId) digits(req.query.accountId, 11, 'accountId'); if (req.query.cardNumber) digits(req.query.cardNumber, 16, 'cardNumber'); let cards = data.cards; if (req.query.accountId) cards = cards.filter(card => card.accountId === id(req.query.accountId)); if (req.query.cardNumber) cards = cards.filter(card => card.number === id(req.query.cardNumber)); if (req.query.accountId && req.query.cardNumber && !cards.length) throw appError(404, 'NOT_FOUND', 'Card is not associated with this account.'); res.json({ data: pagination([...cards].sort((a, b) => a.number.localeCompare(b.number)).map(publicCard), req.query.cursor, req.query.limit, 7) }); } catch (error) { next(error); } });
  app.get('/api/cards/:cardNumber', business, (req, res, next) => { try { const card = store.load().cards.find(item => item.number === cardNumber(req)); if (!card) throw appError(404, 'NOT_FOUND', 'Card not found.'); res.set('ETag', etag(card)).json({ data: publicCard(card) }); } catch (error) { next(error); } });
  app.patch('/api/cards/:cardNumber', business, (req, res, next) => { try { const allowed = ['active', 'embossedName', 'expirationDate']; for (const key of Object.keys(req.body)) if (!allowed.includes(key)) throw appError(422, 'VALIDATION_ERROR', `Unsupported card field: ${key}`); if (!Object.keys(req.body).length || ('active' in req.body && !['Y', 'N'].includes(req.body.active)) || ('embossedName' in req.body && (id(req.body.embossedName).length < 1 || id(req.body.embossedName).length > 50)) || ('expirationDate' in req.body && !dateOnly(req.body.expirationDate))) throw appError(422, 'VALIDATION_ERROR', 'Card fields are invalid.'); const card = store.transaction(data => { const value = data.cards.find(item => item.number === cardNumber(req)); if (!value) throw appError(404, 'NOT_FOUND', 'Card not found.'); requireMatch(req, value); Object.assign(value, req.body); value.version++; return value; }); res.set('ETag', etag(card)).json({ data: publicCard(card) }); } catch (error) { next(error); } });

  app.get('/api/lookup/transaction-types', business, (_req, res) => res.json({ data: store.load().types }));
  app.get('/api/lookup/transaction-categories', business, (req, res, next) => { try { if (req.query.typeCode) digits(req.query.typeCode, 2, 'typeCode'); res.json({ data: store.load().categories.filter(category => !req.query.typeCode || category.typeCode === id(req.query.typeCode)) }); } catch (error) { next(error); } });
  app.get('/api/transactions', business, (req, res, next) => { try { const data = store.load(); if (req.query.cardNumber) digits(req.query.cardNumber, 16, 'cardNumber'); if (req.query.accountId) digits(req.query.accountId, 11, 'accountId'); let transactions = data.transactions; if (req.query.cardNumber) transactions = transactions.filter(item => item.cardNumber === id(req.query.cardNumber)); if (req.query.accountId) { const numbers = new Set(data.cards.filter(card => card.accountId === id(req.query.accountId)).map(card => card.number)); transactions = transactions.filter(item => numbers.has(item.cardNumber)); } res.json({ data: pagination([...transactions].sort((a, b) => a.id.localeCompare(b.id)).map(publicTransaction), req.query.cursor, req.query.limit, 10) }); } catch (error) { next(error); } });
  app.get('/api/transactions/:transactionId', business, (req, res, next) => { try { const transactionId = digits(req.params.transactionId, 16, 'transactionId'); const value = store.load().transactions.find(item => item.id === transactionId); if (!value) throw appError(404, 'NOT_FOUND', 'Transaction not found.'); res.set('ETag', etag(value)).json({ data: publicTransaction(value) }); } catch (error) { next(error); } });
  app.post('/api/transactions', business, (req, res, next) => { try { const idem = idempotency(req, 'POST:/api/transactions'); const result = store.transaction(data => { const previous = replay(data, idem); if (previous) return { ...previous, replay: true }; validateTransaction(req.body, data); const card = data.cards.find(item => item.number === digits(req.body.cardNumber, 16, 'cardNumber')); if (!card || card.active !== 'Y') throw appError(422, 'VALIDATION_ERROR', 'cardNumber must identify an active card.'); const now = new Date().toISOString(); const value = { id: String(data.transactions.reduce((highest, item) => Math.max(highest, Number(item.id) || 0), 0) + 1).padStart(16, '0'), typeCode:id(req.body.typeCode), categoryCode:String(req.body.categoryCode).padStart(4, '0'), source:id(req.body.source), description:id(req.body.description), amount:money(req.body.amount), merchantId:req.body.merchantId ? digits(req.body.merchantId, 9, 'merchantId') : '000000000', merchantName:id(req.body.merchantName).slice(0, 50), merchantCity:id(req.body.merchantCity).slice(0, 50), merchantZip:id(req.body.merchantZip).slice(0, 10), cardNumber:card.number, originatedAt:req.body.originatedAt || now, processedAt:req.body.processedAt || now, version:1 }; data.transactions.push(value); const response = { transaction: publicTransaction(value) }; data.idempotency[idem.key] = { target: idem.target, fingerprint: idem.fingerprint, result: response, createdAt: now }; return { ...response, replay: false }; }); res.status(result.replay ? 200 : 201).set('ETag', '"1"').json({ data: result.transaction, meta: { idempotentReplay: result.replay } }); } catch (error) { next(error); } });

  app.get('/api/billing/:accountId/preview', business, (req, res, next) => { try { const value = store.load().accounts.find(item => item.id === accountId(req)); if (!value) throw appError(404, 'NOT_FOUND', 'Account not found.'); res.set('ETag', etag(value)).json({ data: { accountId: value.id, currentBalance: value.currentBalance, amountDue: Math.max(value.currentBalance, 0), payable: value.currentBalance > 0 } }); } catch (error) { next(error); } });
  app.post('/api/billing/:accountId/pay-full-balance', business, (req, res, next) => { try { const target = `POST:/api/billing/${accountId(req)}/pay-full-balance`; const idem = idempotency(req, target); const result = store.transaction(data => { const previous = replay(data, idem); if (previous) return { ...previous, replay: true }; const account = data.accounts.find(item => item.id === accountId(req)); if (!account) throw appError(404, 'NOT_FOUND', 'Account not found.'); requireMatch(req, account); if (account.currentBalance <= 0) throw appError(409, 'NOTHING_TO_PAY', 'Account has no outstanding balance.'); const xref = data.xrefs.find(item => item.accountId === account.id); const card = xref && data.cards.find(item => item.number === xref.cardNumber && item.accountId === account.id); if (!card) throw appError(422, 'VALIDATION_ERROR', 'Account has no card cross-reference for payment.'); const now = new Date().toISOString(); const value = { id:String(data.transactions.reduce((highest, item) => Math.max(highest, Number(item.id) || 0), 0) + 1).padStart(16, '0'), typeCode:'02', categoryCode:'0002', source:'POS TERM', description:'BILL PAYMENT - ONLINE', amount:money(account.currentBalance), merchantId:'999999999', merchantName:'BILL PAYMENT', merchantCity:'N/A', merchantZip:'N/A', cardNumber:card.number, originatedAt:now, processedAt:now, version:1 }; data.transactions.push(value); account.currentBalance = 0; account.currentCycleCredit = money(account.currentCycleCredit + value.amount); account.version++; const response = { transaction: publicTransaction(value), account: publicAccount(account), accountEtag: etag(account) }; data.idempotency[idem.key] = { target: idem.target, fingerprint: idem.fingerprint, result: response, createdAt: now }; return { ...response, replay:false }; }); res.status(result.replay ? 200 : 201).set('ETag', result.accountEtag).json({ data: { transaction: result.transaction, account: result.account }, meta: { idempotentReplay: result.replay } }); } catch (error) { next(error); } });

  app.post('/api/reports', business, (req, res, next) => { try { const period = req.body.period || 'custom'; let { startDate, endDate } = req.body; const now = new Date(); if (period === 'monthly') { startDate = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}-01`; endDate = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 0)).toISOString().slice(0, 10); } else if (period === 'yearly') { startDate = `${now.getUTCFullYear()}-01-01`; endDate = `${now.getUTCFullYear()}-12-31`; } else if (period !== 'custom') throw appError(422, 'VALIDATION_ERROR', 'period must be monthly, yearly, or custom.'); if (!dateOnly(startDate) || !dateOnly(endDate) || startDate > endDate) throw appError(422, 'VALIDATION_ERROR', 'Use an ordered range of real YYYY-MM-DD dates.'); const report = store.transaction(data => { const rows = data.transactions.filter(item => { const when = effectiveDate(item); return when >= startDate && when <= endDate; }).sort((a, b) => effectiveDate(a).localeCompare(effectiveDate(b)) || a.id.localeCompare(b.id)); const accountFor = item => data.cards.find(card => card.number === item.cardNumber)?.accountId || 'UNASSIGNED'; const totals = new Map(); for (const row of rows) totals.set(accountFor(row), money((totals.get(accountFor(row)) || 0) + row.amount)); const content = ['Daily Transaction Report', `Date Range: ${startDate} to ${endDate}`, 'Transaction ID     Account ID   Type Category Source       Amount', ...rows.map(row => `${row.id} ${accountFor(row).padEnd(11)} ${row.typeCode}   ${row.categoryCode}     ${row.source.padEnd(10)} ${row.amount.toFixed(2)}`), '', ...[...totals.entries()].sort(([a],[b]) => a.localeCompare(b)).map(([account, total]) => `Account Total ${account}: ${total.toFixed(2)}`), `Grand Total: ${money(rows.reduce((sum, row) => sum + row.amount, 0)).toFixed(2)}`].join('\n'); const value = { id:randomUUID(), ownerId:req.session.user.id, status:'completed', period, startDate, endDate, createdAt:new Date().toISOString(), content, version:1 }; data.reports.push(value); return value; }); res.status(201).json({ data: { id: report.id, status: report.status, period:report.period, startDate:report.startDate, endDate:report.endDate } }); } catch (error) { next(error); } });
  function ownReport(req) { const report = store.load().reports.find(item => item.id === id(req.params.reportId)); if (!report) throw appError(404, 'NOT_FOUND', 'Report not found.'); if (report.ownerId !== req.session.user.id) throw appError(403, 'FORBIDDEN', 'Report belongs to another user.'); return report; }
  app.get('/api/reports/:reportId', business, (req, res, next) => { try { const report = ownReport(req); res.json({ data: { id:report.id, status:report.status, period:report.period, startDate:report.startDate, endDate:report.endDate, createdAt:report.createdAt } }); } catch (error) { next(error); } });
  app.get('/api/reports/:reportId/content', business, (req, res, next) => { try { const report = ownReport(req); if (report.status !== 'completed') throw appError(409, 'REPORT_NOT_READY', 'Report has not completed.'); res.type('text/plain').send(report.content); } catch (error) { next(error); } });

  app.get('/api/admin/users', admin, (req, res, next) => { try { res.json({ data: pagination([...store.load().users].sort((a,b) => a.id.localeCompare(b.id)).map(publicUser), req.query.cursor, req.query.limit, 10) }); } catch (error) { next(error); } });
  app.post('/api/admin/users', admin, async (req, res, next) => { try { requireFields(req.body, ['id', 'firstName', 'lastName', 'password', 'role']); const userId = id(req.body.id).toUpperCase(); if (!/^[A-Z0-9]{3,8}$/.test(userId) || !['A', 'U'].includes(req.body.role) || id(req.body.firstName).length > 25 || !id(req.body.firstName) || id(req.body.lastName).length > 25 || !id(req.body.lastName) || String(req.body.password).length < 8) throw appError(422, 'VALIDATION_ERROR', 'id, firstName, lastName, role A/U, and password of at least 8 characters are required.'); const passwordHash = await bcrypt.hash(String(req.body.password), 12); const user = store.transaction(data => { if (data.users.some(item => item.id === userId)) throw appError(409, 'ALREADY_EXISTS', 'User already exists.'); const value = { id:userId, firstName:id(req.body.firstName), lastName:id(req.body.lastName), role:req.body.role, passwordHash, version:1 }; data.users.push(value); return value; }); res.status(201).set('ETag', etag(user)).json({ data: publicUser(user) }); } catch (error) { next(error); } });
  app.get('/api/admin/users/:userId', admin, (req,res,next) => { try { const user = store.load().users.find(item => item.id === userId(req)); if (!user) throw appError(404, 'NOT_FOUND', 'User not found.'); res.set('ETag', etag(user)).json({ data: publicUser(user) }); } catch (error) { next(error); } });
  app.patch('/api/admin/users/:userId', admin, async (req,res,next) => { try { const allowed = ['firstName', 'lastName', 'role', 'password']; for (const key of Object.keys(req.body)) if (!allowed.includes(key)) throw appError(422, 'VALIDATION_ERROR', `Unsupported user field: ${key}`); if (!Object.keys(req.body).length || ('role' in req.body && !['A','U'].includes(req.body.role)) || ('firstName' in req.body && (!id(req.body.firstName) || id(req.body.firstName).length > 25)) || ('lastName' in req.body && (!id(req.body.lastName) || id(req.body.lastName).length > 25)) || ('password' in req.body && String(req.body.password).length < 8)) throw appError(422, 'VALIDATION_ERROR', 'User fields are invalid.'); const passwordHash = req.body.password ? await bcrypt.hash(String(req.body.password), 12) : null; const user = store.transaction(data => { const value = data.users.find(item => item.id === userId(req)); if (!value) throw appError(404, 'NOT_FOUND', 'User not found.'); requireMatch(req, value); for (const key of ['firstName','lastName','role']) if (key in req.body) value[key] = id(req.body[key]); if (passwordHash) value.passwordHash = passwordHash; value.version++; return value; }); res.set('ETag', etag(user)).json({ data: publicUser(user) }); } catch (error) { next(error); } });
  app.delete('/api/admin/users/:userId', admin, (req,res,next) => { try { store.transaction(data => { const index = data.users.findIndex(item => item.id === userId(req)); if (index < 0) throw appError(404, 'NOT_FOUND', 'User not found.'); const user = data.users[index]; requireMatch(req, user); if (user.role === 'A' && data.users.filter(item => item.role === 'A').length === 1) throw appError(409, 'LAST_ADMIN_FORBIDDEN', 'The last administrator cannot be deleted.'); if (user.id === req.session.user.id) throw appError(409, 'SELF_DELETE_FORBIDDEN', 'An administrator cannot delete their own active user.'); data.users.splice(index, 1); }); res.status(204).end(); } catch (error) { next(error); } });
  app.use((_req, _res, next) => next(appError(404, 'NOT_FOUND', 'Route not found.')));
  app.use((error, _req, res, _next) => { const malformed = error instanceof SyntaxError && 'body' in error; const invalidPath = error instanceof URIError; res.status(malformed || invalidPath ? 400 : error.status || 500).json({ error: { code: malformed ? 'INVALID_JSON' : invalidPath ? 'INVALID_PATH' : error.code || 'INTERNAL_ERROR', message: malformed ? 'Request body must be valid JSON.' : invalidPath ? 'Path contains invalid URL encoding.' : error.status ? error.message : 'An unexpected server error occurred.', ...(error.details ? { details:error.details } : {}) } }); });
  return app;
}
