import { CommonModule, DOCUMENT } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, CanActivateFn, NavigationEnd, Router, RouterLink, RouterLinkActive, RouterOutlet, Routes } from '@angular/router';
import { filter } from 'rxjs';
import { Api, ApiError } from './api.service';
import { OverviewComponent, AccountsComponent, CardsComponent, TransactionsComponent, NewTransactionComponent, BillingComponent, ReportsComponent, UsersComponent } from './pages.component';
const errorMessage=(e:unknown)=>(e as ApiError)?.message ?? 'Something went wrong. Please try again.';
export const signedIn:CanActivateFn=()=>{const api=inject(Api),router=inject(Router);return api.user()?true:router.createUrlTree(['/sign-in']);};
const role=(wanted:'A'|'U'):CanActivateFn=>()=>{const api=inject(Api),router=inject(Router);return api.user()?.role===wanted?true:router.createUrlTree(['/not-authorized']);};
export const businessOnly=role('U'); export const adminOnly=role('A');
@Component({selector:'app-root',standalone:true,imports:[RouterOutlet],template:'<router-outlet/>'}) export class AppComponent {}
@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule],template:`<main class="login"><section><div class="brand"><b>CD</b> CardDemo</div><p class="eyebrow">Secure operations portal</p><h1>Sign in to your workspace</h1><p class="muted">Use a demo account to access role-specific banking operations.</p><form [formGroup]="form" (ngSubmit)="submit()"><label>User ID<input formControlName="userId" autocomplete="username" required [attr.aria-invalid]="form.controls.userId.invalid&&form.controls.userId.touched"></label><small *ngIf="form.controls.userId.invalid&&form.controls.userId.touched">User ID is required.</small><label>Password<input type="password" formControlName="password" autocomplete="current-password" required [attr.aria-invalid]="form.controls.password.invalid&&form.controls.password.touched"></label><small *ngIf="form.controls.password.invalid&&form.controls.password.touched">Password is required.</small><p class="error" role="alert" *ngIf="error()">{{error()}}</p><button class="primary" [disabled]="form.invalid||loading()">{{loading()?'Signing in…':'Sign in'}}</button></form><aside><strong>Demo accounts</strong><span>Business: USER0001 / User123!</span><span>Administrator: ADMIN001 / Admin123!</span></aside></section><div class="login-art"><small>CardDemo</small><h2>Confident decisions, clear operations.</h2><p>Manage cards, transactions, billing, and reports from one focused workspace.</p></div></main>`}) export class SignInComponent {private api=inject(Api);private router=inject(Router);private fb=inject(FormBuilder);loading=signal(false);error=signal('');form=this.fb.nonNullable.group({userId:['',Validators.required],password:['',Validators.required]});submit(){if(this.form.invalid){this.form.markAllAsTouched();return;}this.loading.set(true);this.api.signIn(this.form.getRawValue()).subscribe({next:r=>{this.api.user.set(r.data.user);void this.router.navigateByUrl(r.data.user.role==='A'?'/admin/users':'/overview');},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}}
@Component({standalone:true,imports:[CommonModule,RouterLink,RouterLinkActive,RouterOutlet],template:`<div class="shell"><aside><a class="brand" routerLink="/overview"><b>CD</b> CardDemo</a><small>{{api.user()?.role==='A'?'Administrator':'Business operations'}}</small><nav aria-label="Primary navigation"><a *ngFor="let item of links()" [routerLink]="item.path" routerLinkActive="active">{{item.label}}</a></nav><div class="profile"><strong>{{api.user()?.firstName}} {{api.user()?.lastName}}</strong><span>{{api.user()?.role==='A'?'Administrator':'Business user'}}</span><button (click)="logout()">Sign out</button></div></aside><main><header><strong>{{title()}}</strong><button (click)="logout()">Sign out</button></header><div class="content"><router-outlet/></div></main><nav class="mobile-nav" aria-label="Mobile navigation"><a *ngFor="let item of links()" [routerLink]="item.path" routerLinkActive="active">{{item.label}}</a></nav></div>`}) export class ShellComponent {api=inject(Api);private router=inject(Router);private route=inject(ActivatedRoute);private document=inject(DOCUMENT);title=signal('Overview');links=computed(()=>this.api.user()?.role==='A'?[{path:'/admin/users',label:'Users'}]:[{path:'/overview',label:'Overview'},{path:'/accounts',label:'Accounts'},{path:'/cards',label:'Cards'},{path:'/transactions',label:'Transactions'},{path:'/billing',label:'Billing'},{path:'/reports',label:'Reports'}]);constructor(){this.router.events.pipe(filter(e=>e instanceof NavigationEnd)).subscribe(()=>{let r=this.route;while(r.firstChild)r=r.firstChild;const t=r.snapshot.data['title'] as string|undefined;this.title.set(t??'CardDemo');this.document.title=`${this.title()} · CardDemo`;});}logout(){this.api.signOut().subscribe({complete:()=>{this.api.user.set(null);void this.router.navigateByUrl('/sign-in')}})}}
@Component({standalone:true,template:'<section class="panel pad"><h1>Not authorized</h1><p>You do not have access to this workspace.</p></section>'}) export class ForbiddenComponent {}
export const routes:Routes=[{path:'sign-in',component:SignInComponent},{path:'not-authorized',component:ForbiddenComponent},{path:'',component:ShellComponent,canActivate:[signedIn],children:[{path:'overview',component:OverviewComponent,canActivate:[businessOnly],data:{title:'Overview'}},{path:'accounts',component:AccountsComponent,canActivate:[businessOnly],data:{title:'Accounts'}},{path:'cards',component:CardsComponent,canActivate:[businessOnly],data:{title:'Cards'}},{path:'transactions',component:TransactionsComponent,canActivate:[businessOnly],data:{title:'Transactions'}},{path:'transactions/new',component:NewTransactionComponent,canActivate:[businessOnly],data:{title:'Create transaction'}},{path:'billing',component:BillingComponent,canActivate:[businessOnly],data:{title:'Full-balance billing'}},{path:'reports',component:ReportsComponent,canActivate:[businessOnly],data:{title:'Reports'}},{path:'admin/users',component:UsersComponent,canActivate:[adminOnly],data:{title:'Users'}},{path:'',pathMatch:'full',redirectTo:'overview'}]},{path:'**',redirectTo:'sign-in'}];
