import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { SignInComponent, adminOnly, businessOnly, routes } from './app.component';
import { ReportsComponent, UsersComponent } from './pages.component';
import { Api } from './api.service';
describe('workflow components and guards',()=>{it('starts sign-in with blank credentials',()=>{TestBed.configureTestingModule({imports:[SignInComponent],providers:[provideHttpClient(),provideRouter(routes)]});const c=TestBed.createComponent(SignInComponent).componentInstance;expect(c.form.getRawValue()).toEqual({userId:'',password:''});});it('uses a seeded custom report range',()=>{TestBed.configureTestingModule({imports:[ReportsComponent],providers:[provideHttpClient()]});const c=TestBed.createComponent(ReportsComponent).componentInstance;expect(c.form.getRawValue()).toEqual({period:'custom',startDate:'2022-06-01',endDate:'2022-06-30'});});it('requires an eight-character password before creating users',()=>{TestBed.configureTestingModule({imports:[UsersComponent],providers:[provideHttpClient()]});const c=TestBed.createComponent(UsersComponent).componentInstance;c.newUser();c.form.patchValue({password:'short'});expect(c.form.controls.password.valid).toBeFalse();c.form.patchValue({password:'LongPass1'});expect(c.form.controls.password.valid).toBeTrue();});it('routes mismatched roles to not-authorized',()=>{TestBed.configureTestingModule({providers:[provideHttpClient(),provideRouter(routes),Api]});const api=TestBed.inject(Api);api.user.set({id:'A',firstName:'A',lastName:'A',role:'A'});const result=TestBed.runInInjectionContext(()=>businessOnly({} as never,{} as never));expect((result as any).toString()).toContain('/not-authorized');api.user.set({id:'U',firstName:'U',lastName:'U',role:'U'});const admin=TestBed.runInInjectionContext(()=>adminOnly({} as never,{} as never));expect((admin as any).toString()).toContain('/not-authorized');});});
import { CursorHistory, DataTableComponent, orderedDates, validDate } from './pages.component';
describe('review regressions',()=>{
 it('produces valid in-table empty state markup',()=>{TestBed.configureTestingModule({imports:[DataTableComponent]});const f=TestBed.createComponent(DataTableComponent);f.componentRef.setInput('items',[]);f.componentRef.setInput('kind','transaction');f.componentRef.setInput('caption','Transactions');f.detectChanges();const table=f.nativeElement.querySelector('table');expect(table.querySelector('tbody tr td[colspan="4"]')?.textContent).toContain('No records');expect(table.querySelector('tbody div')).toBeNull();});
 it('validates blank and malformed account fields before submit',()=>{TestBed.configureTestingModule({imports:[ReportsComponent],providers:[provideHttpClient()]});const c=TestBed.createComponent(ReportsComponent).componentInstance;c.form.patchValue({startDate:'',endDate:''});expect(c.form.invalid).toBeTrue();});
 it('requires valid ordered custom report dates',()=>{TestBed.configureTestingModule({imports:[ReportsComponent],providers:[provideHttpClient()]});const form=TestBed.createComponent(ReportsComponent).componentInstance.form;form.patchValue({period:'custom',startDate:'2022-06-30',endDate:'2022-06-01'});expect(form.errors?.['dateOrder']).toBeTrue();form.patchValue({endDate:'2022-06-30'});expect(form.valid).toBeTrue();expect(validDate({value:'2022-02-29'} as any)?.['date']).toBeTrue();});
 it('tracks page cursor history and resets stale cursors',()=>{const history=new CursorHistory();history.next='p2';history.advance('p2');history.next='p3';history.advance('p3');expect(history.moveBack()).toBe('p2');expect(history.moveBack()).toBe('');history.reset();expect(history.next).toBe('');expect(history.previous).toEqual([]);});
});
