#!/usr/bin/env python3
"""Generate TypeScript validation lookups from the immutable CSLKPCDY copybook."""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / '00.phase-1-input/cpy/CSLKPCDY.cpy'
OUTPUT = ROOT / 'src/common/validation/legacy-validation-lookups.ts'


def values_between(text: str, start: str, end: str | None) -> list[str]:
    section = text.split(start, 1)[1]
    if end:
        section = section.split(end, 1)[0]
    return re.findall(r"'([^']+)'", section)


def ts_array(name: str, values: list[str]) -> str:
    entries = ',\n'.join(f"  '{value}'" for value in values)
    return f"export const {name} = [\n{entries},\n] as const;"


def main() -> None:
    text = SOURCE.read_text(encoding='utf-8')
    source_hash = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    phone = values_between(text, 'VALID-PHONE-AREA-CODE', 'VALID-GENERAL-PURP-CODE')
    general = values_between(text, 'VALID-GENERAL-PURP-CODE', 'VALID-EASY-RECOG-AREA-CODE')
    easy = values_between(text, 'VALID-EASY-RECOG-AREA-CODE', 'US-STATE-CODE-TO-EDIT')
    states = values_between(text, 'VALID-US-STATE-CODE', 'US-STATE-ZIPCODE-TO-EDIT')
    state_zip = values_between(text, 'VALID-US-STATE-ZIP-CD2-COMBO', 'LAST-3-OF-ZIP')

    content = f'''/**
 * GENERATED by scripts/generate-legacy-validation-lookups.py.
 *
 * Source: 00.phase-1-input/cpy/CSLKPCDY.cpy
 * SHA-256: {source_hash}
 * Do not edit manually; regenerate after an explicitly reviewed source change.
 */

export const CSLKPCDY_SOURCE_SHA256 =
  '{source_hash}' as const;

{ts_array('NORTH_AMERICAN_PHONE_AREA_CODES', phone)}

{ts_array('GENERAL_PURPOSE_PHONE_AREA_CODES', general)}

{ts_array('EASY_RECOGNITION_PHONE_AREA_CODES', easy)}

{ts_array('US_STATE_CODES', states)}

{ts_array('US_STATE_ZIP_PREFIX_COMBINATIONS', state_zip)}

/** COACTUPC tests this lookup category for phone-number validation. */
export const LEGACY_PHONE_AREA_CODE_SET = new Set<string>(GENERAL_PURPOSE_PHONE_AREA_CODES);
export const LEGACY_US_STATE_CODE_SET = new Set<string>(US_STATE_CODES);
export const LEGACY_US_STATE_ZIP_PREFIX_SET = new Set<string>(US_STATE_ZIP_PREFIX_COMBINATIONS);
'''
    OUTPUT.write_text(content, encoding='utf-8')


if __name__ == '__main__':
    main()
